# top level stuff you probably don't need to touch
highlighter: rouge
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://joaonzangoii.github.io/
baseurl: /
title: Tchiowa Hacker
author: Jo√£o Nzango
description: Blog Pessoal e CV
avatar: profile.jpg
email: joaonzango@gmail.com
github: /joaonzangoII/joaonzangoii.github.com # username
twitter: joaonzango
linkedin: joaonzangoii
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: joaonzangoii-github-io
google_analytics: UA-47484774-5
website: joaonzangoii.github.io
website_full: https://joaonzangoii.github.io


# needed for travis-ci build
exclude: [vendor]
